name: web-ocr

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    command: npm start
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    volumes:
      - ./backend/app:/code/app
    ports:
      - "9004:9004"
