version: '3'
services:
  # db:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./db_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  frontend:
    build: ./docker_frontend
    volumes:
      - ./frontend_app:/usr/src/app
    command: sh -c "cd front_app && npm start"
    ports:
      - "3000:3000"
  backend:
    build: ./docker_backend
    volumes:
      - ./backend_app/src:/app
    ports:
      - "9004:9004"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 9004
    # depends_on:
    #   - db
